### ISSUE TITLE
Do no render section when it is empty

### ISSUE THREAD

**Issue by Nightliss** [15adhami/XmlExtensions#12]
Hi, the sections with an empty `<settings />` render empty boxes:

![image](https://user-images.githubusercontent.com/30467858/133304757-f9c05338-bad7-4f8b-ab24-4f0b23e0b6d3.png)

I'm dynamically adding settings with `PatchOperationAdd` using `<tag>` node. When the operation is not ran, nothing is inserted but it still renders. Seems like a bug :)

**Comment by 15adhami** [comment]
Fixed. Thanks for the report!
