### ISSUE TITLE
Black Screen Issue

### ISSUE THREAD

**Issue by TheOldOne822** [15adhami/XmlExtensions#13]
I am having a black screen issue like some on the Steam workshop comments have described where the game will load to a black screen and be unplayable. It started when XmlExtensions was updated this morning.

Issue happens for me only when XmlExtensions, Expanded Materials - Plastics and Expanded Materials - Metals (either normal or lite) are loaded together. Removing any one of the 3 resolves the issue. Issue shows when they + Harmony are the only 4 mods loaded.

I would leave this as a comment on the Steam workshop so others with this issue can see it but I have the GOG version of Rimworld so can't leave Steam workshop comments.

**Comment by 15adhami** [comment]
Fixed.
