### ISSUE TITLE
Recommended additions

### ISSUE THREAD

**Issue by kaedys** [15adhami/XmlExtensions#9]
First off, love the mod.  Reading over the wiki, some recommended additions based on the patches I've been writing:

----
**PatchOperationSafeRemove**
Just like SafeAdd, removes it if it exists, doesn't complain if it already doesn't exist.  Basically a compact PatchOperationConditional -> Match -> PathOperationRemove, a way of saying "I want to guarantee this node does not exist, regardless of whether it currently does or not".
 
----

**PatchOperation[Add/Replace/Remove]PostProcess**
XML patches occur _before_ parent relationships are accounted for, so if a node receives a child or list element from a parent, a patch operation cannot replace or remove it in the child because it's not _in_ the child in the XML (and mutating the parent may have secondary implications).  For regular nodes, this isn't really an issue for Add and Replace, since the child can simply redefine the key, but children can't easily have a Remove operation run against a node received from a parent, and lists are always concatenated with parents unless you want to throw away the entire inherited list using `Inherit="False"`, so trying to remove one specific list element (ex. CompQuality) from an item that inherited that element from a parent is not particularly straightforward, or easily compatible with other patches.

Now, the combination of AddOrReplace, SafeAdd, and SafeRemove _may_ be sufficient for this use case already, but I'm not sure, it depends on the implementation.  And this is presuming this mod's patch actions act _after_ the XML has been processed into C# classes and not between XML reading/concatenating and XML processing (if it acts before processing into classes, it'll have the same limitation, so this goes out the window by default).

A notable specific use case examples for this, as noted above, would be removing the CompQuality list element from the `comps` node in an item with a long inheritance chain.  For example, the Gunlink, which inherits that element via the parent chain `Apparel_Gunlink -> ApparelArmorHelmetReconBase -> ArmorHelmetMakeableBase -> ArmorMachineableBase -> ApparelBase`.  Removing it from `ApparelBase` is obviously a non-starter, leaving the only options being to rebuild the def sourcing from `ApparelNoQualityBase`, including all elements added by the 3 other intermediate defs (and failing to capture any other patches that occur to those intermediate defs), or doing an `Inherit="False"` PatchOperationAdd/Replace on the entire `comps` block, and thus discarding any other comps added by other patches to the Gunlink def or any of its parents.

----

**PatchOperationMerge**
Takes a node or nodes in the value, and for each element, does the following:
* If the element is present in `value` but not in `xpath`, adds it.
* If the element is present in `xpath` but not in `value`, retains it as is.
* If the element is present in both `value` and `xpath`, replaces the element in `xpath` with the element in `value`.
* For replacement operations, operates recursively, in that rather than a straight replacement of the node, if that node has children, those children will be evaluated in the same way as above.
* Supports an optional parameter `recursionDepth`, that works like `safetyDepth` in SafeAdd.  If specified to a non-negative number, will only recurse to that level, and any nodes replaced at that level will not parse their children using the merge mechanism, but instead the entire node will be replaced.  If negative, recurses all child nodes.

For example, given:

```
<ThingDef Name="Foo">
    <category>Item</category>
    <statBases>
        <Mass>10</Mass>
        <WorkToMake>30000</WorkToMake>
    </statBases>
</ThingDef>
```
And
```
<Operation Class="XmlExtensions.PatchOperationMerge">
    <xpath>/Defs/ThingDef[@Name="Foo"]</xpath>
    <recursionDepth>-1</recursionDepth>
    <value>
        <ThingDef Name="Foo">
            <defName>FooBar</defname>
            <statBases>
                <MaxHitPoints>100</MaxHitPoints>
                <WorkToMake>150000</WorkToMake>
                <Flammability>1.0</Flammability>
            </statBases>
        </ThingDef>
    </value>
</Operation>
```
The result would be:
```
<ThingDef Name="Foo">
    <defName>FooBar</defname>
    <category>Item</category>
    <statBases>
        <Mass>10</Mass>
        <MaxHitPoints>100</MaxHitPoints>
        <WorkToMake>150000</WorkToMake>
        <Flammability>1.0</Flammability>
    </statBases>
</ThingDef>
```
The `defName` element at depth 1 was added, as it was not present in the target def.  `category` was retained, as it was in the target def but not the value def.  `statBases` is present in both, and recursion depth is set to infinite (`-1`), so its children are in turn evaluated.  `Mass` is retained, as it is only in the target def and not the value def.  `MaxHitPoints` and `Flammability` were added, as they were only in the value def.  Lastly, `WorkToMake` was replaced, as it was present in both.

If `<recursionDepth>` was instead set to 1, the result would be:
```
<ThingDef Name="Foo">
    <defName>FooBar</defname>
    <statBases>
        <MaxHitPoints>100</MaxHitPoints>
        <WorkToMake>150000</WorkToMake>
        <Flammability>1.0</Flammability>
    </statBases>
</ThingDef>
```
`statBases` is at depth 1, so its children are not evaluated, and the full `statBases` node in the value simply replaces what it's the target def at that node, and any children that were in the target def but not the value def (ex. `Mass`) are simply obliterated, as if a normal `PatchOperationReplace` on `statBases` had been run.

Primary use case is being able to block Add/Replace to a node with children, without having to individually handle each field, and while still playing nicely with other patches that mutate other fields in that node.  For example, in my local patch of some weapons, when mutating the accuracy, I have to individually target and replace each AccuracyX element in a separate PatchOperationReplace.  With Merge, I could just specify:
```
<value>
    <statBases>
        <AccuracyTouch>0.85</AccuracyTouch>
        <AccuracyShort>0.80</AccuracyShort>
        <AccuracyMedium>0.53</AccuracyMedium>
        <AccuracyLong>0.30</AccuracyLong>
    </statBases>
</value>
```
This would add or replace those 4 fields in `statsBases`, but leave any other fields alone.  This would, in theory, permit the 10-11 patch operations I currently run _per weapon_ to be only 3, one for the weapon def, one for the `Verb_Shoot` verb list element (since Merge doesn't really work with list elements), and one for the projectile.  Less chance of error, easier to verify all the values are set properly, and much easier to code in the first place.

**Comment by 15adhami** [comment]
Great suggestions! I should be able to add all of these operations. Only thing is that I'm not sure how PatchOperationSafeRemove would behave in this scenario:

Lets say we wanna remove this node using PatchOperationSafeRemove:
<nodeA>
    <nodeB>someValue</nodeB>
</nodeA>

So if nodeA already exists in the xpath but does not have nodeB as a child, will the entire nodeA be deleted? Or would nothing happen at all? what if that node already has nodeB as a child? What is some other node, nodeC is a child of the nodeA in the xpath?

**Comment by kaedys** [comment]
The way I'd envisioned it working is similar to a vanilla PatchOperationRemove, where you don't give it a value, just a path.  I'm not _completely_ sure what specifically you're asking there, but I'll try to go through some examples and see if I hit the mark.

----
```
<Defs>
    <nodeA>
        <nodeB>someValue</nodeB>
    </nodeA>
</Defs>
```
```
<Operation Class="PatchOperationSafeRemove>
    <xpath>/Defs/nodeA/nodeB</xpath>
</Operation>
```
Result:
```
<Defs>
    <nodeA>
    </nodeA>
</Defs>
```
----
```
<Defs>
    <nodeA>
        <nodeB>someValue</nodeB>
    </nodeA>
</Defs>
```
```
<Operation Class="PatchOperationSafeRemove>
    <xpath>/Defs/nodeA</xpath>
</Operation>
```
Result:
```
<Defs>
</Defs>
```

----
```
<Defs>
    <nodeA>
        <nodeC>someValue</nodeC>
    </nodeA>
</Defs>
```
```
<Operation Class="PatchOperationSafeRemove>
    <xpath>/Defs/nodeA/nodeB</xpath>
</Operation>
```
Result:
```
<Defs>
    <nodeA>
    </nodeA>
</Defs>
```
No change, no error, and no affect on nodeA or nodeC, as they are not the final element of the xpath.  Only the final element would be affected by the operation, just like a normal PatchOperationRemove.  Of course, if you remove nodeA instead here, any children of it would be removed along with it, but if you remove /nodeA/nodeB, then /nodeA and /nodeA/nodeC shouldn't be affected, regardless of whether /nodeA/nodeB exists or not.

Basically, this:
```
<Operation Class="PatchOperationSafeRemove>
    <xpath>/Defs/nodeA/nodeB</xpath>
</Operation>
```
Should act 100% identical to:
```
<Operation Class="PatchOperationConditional">
    <xpath>/Defs/nodeA/nodeB</xpath>
    <match Operation="PatchOperationRemove">
        <xpath>/Defs/nodeA/nodeB</xpath>
    </match>
</Operation>
```
If the element specified by the path exists, it gets deleted.  If it doesn't, whether that's because it doesn't exist or because some element higher in the path doesn't exist, the patch operation simply silently no-ops.

Actually, on that "silently" note, it may be worth having a optional `<log>true</log>` parameter in each of these patch operation, that would spit a line out into the log for the given patch operation saying what it did or didn't do.  For example, this operation, if that parameter were set, might print in the log `xpath '/Defs/nodeA/nodeB' removed` or `xpath '/Defs/nodeA/nodeB' not removed because '/Defs/nodeA' does not exist` (as a normal log event, not an error, just there for debugging).

**Comment by kaedys** [comment]
Oh, also, re-reading my initial post here:

> one for the Verb_Shoot verb list element (since Merge doesn't really work with list elements), and one for the projectile.

I'm not sure how to handle this specific use case.  My intuitive approach would be for Merge to simply work identically to Add for any list elements encountered, because I can't really think of a reliable way to identify list elements.  Basically, if a list is specified in Merge (or as a child node that Merge encounters in its recursing), then Merge would just add the list element(s) to the same list in the target, or create that list node in the target and then add the element(s) to the new (empty) list.  If a user wants to specifically merge on a list element, they can run a separate Merge call using an xpath that properly identifies that list element (by index or by element attribute (ex. Class) or by some subfield value or w/e).

**Comment by 15adhami** [comment]
I've added PatchOperationSafeRemove. I'll try to add the other operations later. Thanks for your help; I really appreciate it. I have uploaded a new beta release here: https://github.com/15adhami/XmlExtensions/releases/tag/B1.1 If you want you may use this to start creating mods or do some testing. I don't imagine the syntax of my operations changing too much so you can get started on using this already. If you decide to use it, could you let me know of any bugs you see? I haven't had any chances to do any actual testing.

**Comment by kaedys** [comment]
Apologies, I've not had time to test this, been putting out fires in production for the last week =/

**Comment by 15adhami** [comment]
No worries, I've also been busy the past week and barely made any progress on this mod.

**Comment by 15adhami** [comment]
I have officially released the mod now, located here: https://steamcommunity.com/sharedfiles/filedetails/?id=2574315206. I will try to add the other patch operations later. I looked a bit into the post-inheritance patching, but the way it's implemented in rimworld is kinda annoying and requires more work that I was expecting originally. I would really love to see these patch operation implemented and will do it as soon I can; I can think of many uses for them. Thanks for all the help and suggestions!

**Comment by idkman2021** [comment]
> First off, love the mod. Reading over the wiki, some recommended additions based on the patches I've been writing:
> 
> **PatchOperationSafeRemove**
> Just like SafeAdd, removes it if it exists, doesn't complain if it already doesn't exist. Basically a compact PatchOperationConditional -> Match -> PathOperationRemove, a way of saying "I want to guarantee this node does not exist, regardless of whether it currently does or not".
> 
> **PatchOperation[Add/Replace/Remove]PostProcess**
> XML patches occur _before_ parent relationships are accounted for, so if a node receives a child or list element from a parent, a patch operation cannot replace or remove it in the child because it's not _in_ the child in the XML (and mutating the parent may have secondary implications). For regular nodes, this isn't really an issue for Add and Replace, since the child can simply redefine the key, but children can't easily have a Remove operation run against a node received from a parent, and lists are always concatenated with parents unless you want to throw away the entire inherited list using `Inherit="False"`, so trying to remove one specific list element (ex. CompQuality) from an item that inherited that element from a parent is not particularly straightforward, or easily compatible with other patches.
> 
> Now, the combination of AddOrReplace, SafeAdd, and SafeRemove _may_ be sufficient for this use case already, but I'm not sure, it depends on the implementation. And this is presuming this mod's patch actions act _after_ the XML has been processed into C# classes and not between XML reading/concatenating and XML processing (if it acts before processing into classes, it'll have the same limitation, so this goes out the window by default).
> 
> A notable specific use case examples for this, as noted above, would be removing the CompQuality list element from the `comps` node in an item with a long inheritance chain. For example, the Gunlink, which inherits that element via the parent chain `Apparel_Gunlink -> ApparelArmorHelmetReconBase -> ArmorHelmetMakeableBase -> ArmorMachineableBase -> ApparelBase`. Removing it from `ApparelBase` is obviously a non-starter, leaving the only options being to rebuild the def sourcing from `ApparelNoQualityBase`, including all elements added by the 3 other intermediate defs (and failing to capture any other patches that occur to those intermediate defs), or doing an `Inherit="False"` PatchOperationAdd/Replace on the entire `comps` block, and thus discarding any other comps added by other patches to the Gunlink def or any of its parents.
> 
> **PatchOperationMerge**
> Takes a node or nodes in the value, and for each element, does the following:
> 
> * If the element is present in `value` but not in `xpath`, adds it.
> * If the element is present in `xpath` but not in `value`, retains it as is.
> * If the element is present in both `value` and `xpath`, replaces the element in `xpath` with the element in `value`.
> * For replacement operations, operates recursively, in that rather than a straight replacement of the node, if that node has children, those children will be evaluated in the same way as above.
> * Supports an optional parameter `recursionDepth`, that works like `safetyDepth` in SafeAdd.  If specified to a non-negative number, will only recurse to that level, and any nodes replaced at that level will not parse their children using the merge mechanism, but instead the entire node will be replaced.  If negative, recurses all child nodes.
> 
> For example, given:
> 
> ```
> <ThingDef Name="Foo">
>     <category>Item</category>
>     <statBases>
>         <Mass>10</Mass>
>         <WorkToMake>30000</WorkToMake>
>     </statBases>
> </ThingDef>
> ```
> 
> And
> 
> ```
> <Operation Class="XmlExtensions.PatchOperationMerge">
>     <xpath>/Defs/ThingDef[@Name="Foo"]</xpath>
>     <recursionDepth>-1</recursionDepth>
>     <value>
>         <ThingDef Name="Foo">
>             <defName>FooBar</defname>
>             <statBases>
>                 <MaxHitPoints>100</MaxHitPoints>
>                 <WorkToMake>150000</WorkToMake>
>                 <Flammability>1.0</Flammability>
>             </statBases>
>         </ThingDef>
>     </value>
> </Operation>
> ```
> 
> The result would be:
> 
> ```
> <ThingDef Name="Foo">
>     <defName>FooBar</defname>
>     <category>Item</category>
>     <statBases>
>         <Mass>10</Mass>
>         <MaxHitPoints>100</MaxHitPoints>
>         <WorkToMake>150000</WorkToMake>
>         <Flammability>1.0</Flammability>
>     </statBases>
> </ThingDef>
> ```
> 
> The `defName` element at depth 1 was added, as it was not present in the target def. `category` was retained, as it was in the target def but not the value def. `statBases` is present in both, and recursion depth is set to infinite (`-1`), so its children are in turn evaluated. `Mass` is retained, as it is only in the target def and not the value def. `MaxHitPoints` and `Flammability` were added, as they were only in the value def. Lastly, `WorkToMake` was replaced, as it was present in both.
> 
> If `<recursionDepth>` was instead set to 1, the result would be:
> 
> ```
> <ThingDef Name="Foo">
>     <defName>FooBar</defname>
>     <statBases>
>         <MaxHitPoints>100</MaxHitPoints>
>         <WorkToMake>150000</WorkToMake>
>         <Flammability>1.0</Flammability>
>     </statBases>
> </ThingDef>
> ```
> 
> `statBases` is at depth 1, so its children are not evaluated, and the full `statBases` node in the value simply replaces what it's the target def at that node, and any children that were in the target def but not the value def (ex. `Mass`) are simply obliterated, as if a normal `PatchOperationReplace` on `statBases` had been run.
> 
> Primary use case is being able to block Add/Replace to a node with children, without having to individually handle each field, and while still playing nicely with other patches that mutate other fields in that node. For example, in my local patch of some weapons, when mutating the accuracy, I have to individually target and replace each AccuracyX element in a separate PatchOperationReplace. With Merge, I could just specify:
> 
> ```
> <value>
>     <statBases>
>         <AccuracyTouch>0.85</AccuracyTouch>
>         <AccuracyShort>0.80</AccuracyShort>
>         <AccuracyMedium>0.53</AccuracyMedium>
>         <AccuracyLong>0.30</AccuracyLong>
>     </statBases>
> </value>
> ```
> 
> This would add or replace those 4 fields in `statsBases`, but leave any other fields alone. This would, in theory, permit the 10-11 patch operations I currently run _per weapon_ to be only 3, one for the weapon def, one for the `Verb_Shoot` verb list element (since Merge doesn't really work with list elements), and one for the projectile. Less chance of error, easier to verify all the values are set properly, and much easier to code in the first place.

is recursionDepth vanilla or are you suggesting it?

**Comment by idkman2021** [comment]
because i needed recursionDepth in my mod

**Comment by idkman2021** [comment]
can i use it for patch operation remove?

**Comment by kaedys** [comment]
I was suggesting adding it.  To my knowledge, vanilla has no concept of recursion for patch calls, in any form.
